name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Building the installer
      run: |
        "Compile_Script.bat"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2
      with:
        path: "Output/setup.exe"
        name: wininstaller-inno-asis
